name: Main
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        image: [windows-latest]
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.github/nuget-packages
    steps:
      - uses: actions/checkout@v2

      - name: NuGet Cache
        uses: actions/cache@v1.1.0
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}.nuget.${{ hashFiles('**/*.fsproj') }}
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.101'

      - name: Install OpenCL
        run: |
          set NUGETDIR=C:\NUGET
          nuget install opencl-nug -Version 0.777.77 -OutputDirectory %NUGETDIR%
          dir %NUGETDIR%\opencl-nug.0.777.77\build\native\
          set OCL_ROOT=%NUGETDIR%\opencl-nug.0.777.77\build\native
          # Install OpenCL Runtime
          choco install opencl-intel-cpu-runtime

      - name: Build .NET Assemblies
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test --configuration Release